machines:
  tour:
    mac: "f4:93:9f:eb:56:a8"
    ip: "192.168.1.167"
    tasks:
      - name: Open Satisfactory
        icon_url: "https://www.pngkit.com/png/full/638-6381661_satisfactory-logo-full-color-square-number.png"
        command: ["steam", "steam://rungameid/526870"]
