services:
  test-machine:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: test-machine
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Etc/UTC
      - SUDO_ACCESS=true
      - USER_NAME=oscar
      - LOG_STDOUT=true
    volumes:
      - ./config/sshd/config:/config
    ports:
      - 2222:2222
    restart: unless-stopped
  front:
    build:
      context: ../wol-panel
      dockerfile: ../wol-panel/Dockerfile.dev
    user: "${UID}:${GID}"
    volumes:
      - ../wol-panel:/app
    ports:
      - 3000:3000
    restart: unless-stopped
  back:
    image: gitea.eldolfin.top/eldolfin/wol-api:latest
    build: ../wol-api
    restart: unless-stopped
    environment:
      - RUST_LOG=debug
    volumes:
      - "/home/oscar/Prog/wol/dev/wol-config.yml:/app/config.yml"
      - "/home/oscar/.ssh/id_ed25519:/root/.ssh/id_ed25519"
  front-tests:
    build:
      context: ../wol-panel
      dockerfile: ../wol-panel/Dockerfile.test
    user: "${UID}:${GID}"
    volumes:
      - ../wol-panel:/app
    ports:
      - 9323:9323
    restart: unless-stopped
