services:
  test-machine:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: test-machine
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Etc/UTC
      - SUDO_ACCESS=true
      - USER_NAME=oscar
      - LOG_STDOUT=true
      - PUBLIC_KEY_FILE=/ssh/public_key
    volumes:
      - ./config/sshd/config:/config
      - ./ssh/id_ed25519.pub:/ssh/public_key
    ports:
      - 2222:2222
    restart: unless-stopped
  front:
    build:
      context: ../
      dockerfile: ./wol-panel/Dockerfile.dev
    user: "${UID}:${GID}"
    volumes:
      - ../wol-panel:/app/wol-panel
      - ../vdi:/app/vdi
    ports:
      - 3000:3000
    restart: unless-stopped
