ssh:
  private_key_file: "/home/oscar/.ssh/id_ed25519"
machines:
  testing-docker-container:
    mac: "02:42:ac:12:00:02"
    ip: "test-machine:2222"
    tasks:
      - name: Fake task
        icon_url: "https://www.pngkit.com/png/full/638-6381661_satisfactory-logo-full-color-square-number.png"
        command: ["echo", "hello", "world"]
