export RUST_LOG := "info,wol_relay_server=debug,agent=debug,backend=debug"
# export RUST_LOG := "debug"
export RUST_LOG_STYLE := "always"

default:
    @just --list

fmt:
    treefmt

run *ARGS:
    cargo run {{ARGS}}

watch-cargo *ARGS:
     git ls-files | entr -cr cargo {{ARGS}}

watch *ARGS:
     @just watch-cargo run {{ARGS}}

lint:
    cargo clippy

watch-agent:
    @just watch --bin agent -- reel ws://localhost:3030

watch-backend:
    @just watch --bin backend -- -c ../dev/wol-config.yml

flamegraph-agent:
    sudo echo -1 | sudo tee /proc/sys/kernel/perf_event_paranoid
    export CARGO_PROFILE_RELEASE_DEBUG=true
    cargo flamegraph --bin agent -- reel ws://127.0.0.1:3030

watch-test:
    export RUST_LOG="debug"
    @just watch-cargo nextest run -j num-cpus --fail-fast
