# export RUST_LOG := "wol_relay_server=debug"
export RUST_LOG := "debug"
export RUST_LOG_STYLE := "always"

default:
    @just --list

# Auto-format the source tree
fmt:
    treefmt

# Run 'cargo run' on the project
run *ARGS:
    cargo run {{ARGS}}

# Run 'cargo watch' to run the project (auto-recompiles)
watch *ARGS:
     git ls-files | entr -cr cargo run {{ARGS}}

lint:
    cargo clippy
