services:
  wol-api:
    image: todo-api:non-existant-tag
    build: ../wol-api
    restart: unless-stopped
    environment:
      - RUST_LOG=debug
    volumes:
      - "./wol-config.yml:/app/config.yml"
      - "~/.ssh/id_ed25519:/root/.ssh/id_ed25519"

  wol-panel:
    image: todo-panel:non-existant-tag
    build: ../wol-panel
    restart: unless-stopped
    depends_on:
      - wol-api

  caddy:
    image: caddy:2.9-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      # - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
