services:
  wol-api:
    image: gitea.eldolfin.top/eldolfin/wol-api:latest
    build: ../wol-api
    restart: unless-stopped
    network_mode: host
    environment:
      - RUST_LOG=debug
    volumes:
      - "/home/oscar/wol-api/deploy/wol-config.yml:/app/config.yml"
      - "~/.ssh/id_ed25519:/root/.ssh/id_ed25519"

  wol-panel:
    image: gitea.eldolfin.top/eldolfin/wol-panel:latest
    build: ../wol-panel
    restart: unless-stopped
    depends_on:
      - wol-api

  caddy:
    image: caddy:2.9-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /home/oscar/wol-api/deploy/Caddyfile:/etc/caddy/Caddyfile
      # - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
