ssh:
  private_key_file: "/root/.ssh/id_ed25519"
machines:
  tour:
    mac: "f4:93:9f:eb:56:a8"
    ip: "192.168.1.167:22"
    tasks:
      # uninstalled...
      # - name: Open Satisfactory
      #   icon_url: "https://www.pngkit.com/png/full/638-6381661_satisfactory-logo-full-color-square-number.png"
      #   command:
      #     ["DISPLAY=:0 steam steam://rungameid/526870 >/dev/null 2>&1 & disown"]
      - name: Rick roll
        icon_url: "https://lh3.googleusercontent.com/JV4zj1L5NT1RBjs8Miz_HpkywVPw8Q0IVlNccTGkjqagAw8zmnn5LFP5PUU1lL1vX6alOFYMXbcy1Orq_x199m8MBA=s128-rj-sc0x00ffffff"
        command:
          [
            "pamixer --set-volume 80 && DISPLAY=:0 mpv --no-resume-playback -fs 'https://youtu.be/dQw4w9WgXcQ' >/dev/null 2>&1 & disown; sleep 5 && DISPLAY=:0 i3-msg workspace 2 && DISPLAY=:0 mpv --no-resume-playback -fs ~/Videos/gameplay_large.mp4 >/dev/null 2>&1 & disown",
          ]
      - name: Upgrade nixos
        icon_url: "https://static-00.iconduck.com/assets.00/nixos-icon-512x445-bskgvwu7.png"
        command:
          [
            "(DISPLAY=:0 alacritty -e systemswitch.py -u -b; sudo shutdown 0) >/dev/null 2>&1 & disown",
          ]
      - name: xeyes
        icon_url: "https://upload.wikimedia.org/wikipedia/commons/8/88/Noia_64_apps_xeyes.png"
        command:
          [
            "DISPLAY=:0 nix shell nixpkgs#xorg.xeyes --command xeyes >/dev/null 2>&1 & disown",
          ]
  oracle:
    mac: "00:00:00:00:00:00" # Whatever, we can't send a wake on lan anyways
    ip: "192.168.27.90:22"
    tasks:
      - name: xeyes
        icon_url: "https://upload.wikimedia.org/wikipedia/commons/8/88/Noia_64_apps_xeyes.png"
        command:
          [
            "DISPLAY=:0 nix shell nixpkgs#xorg.xeyes --command xeyes >/dev/null 2>&1 & disown",
          ]
