services:
  openssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: openssh-server
    hostname: openssh-server #optional
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Etc/UTC
      - SUDO_ACCESS=true
      - USER_NAME=oscar
      - LOG_STDOUT=true
    volumes:
      - ./config/sshd/config:/config
    ports:
      - 2222:2222
