import type { Client } from "openapi-fetch";
import type { InjectionKey } from "vue";
import type { paths } from "./lib/api/v1"; // generated by openapi-typescript
import type { TerminalState } from "./lib/utils/terminal_state";

export type ApiClient = Client<paths>;

export const api_client = Symbol() as InjectionKey<ApiClient>;
export const terminal_pane_provide = Symbol() as InjectionKey<TerminalState>;

const VITE_WOL_API_URL = import.meta.env.VITE_WOL_API_URL;
const api_path =
  VITE_WOL_API_URL === "/" ? window.location.href : VITE_WOL_API_URL;
export const baseUrl = new URL(api_path);
export const wsUrl = `ws://${baseUrl.host}`;
