import type { Client } from "openapi-fetch";
import type { InjectionKey } from "vue";
import type { paths } from "./lib/api/v1"; // generated by openapi-typescript

export type ApiClient = Client<paths>;

export const api_client = Symbol() as InjectionKey<ApiClient>;

const VITE_WOL_API_URL = import.meta.env.VITE_WOL_API_URL;
const api_path =
  VITE_WOL_API_URL === "/" ? window.location.href : VITE_WOL_API_URL;
export const baseUrl = new URL(api_path);
export const wsUrl = `ws://${baseUrl.host}`;
