import type { Client } from "openapi-fetch";
import type { InjectionKey } from "vue";
import type { paths } from "./lib/api/v1"; // generated by openapi-typescript

export type ApiClient = Client<paths>;

export const api_client = Symbol() as InjectionKey<ApiClient>;
