[[language]]
name = "vue"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "vue"] }
language-servers = ["vuels", "typescript-language-server", "scls"] # Emmet en snippet completion for the last 2

[[language-server.typescript-language-server.config.plugins]]
name = "@vue/typescript-plugin"
location = "node_modules/@vue/typescript-plugin"
languages = ["vue"]

[langage-server.vuels]
command = "node_modules/@vue/language-server/bin/vue-language-server.js"
args = ["--stdio"]
config = { typescript = { tsdk = "node_modules/typescript/lib/" } }
