name: "Build docker image and deploy"
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Docker
        run: curl -fsSL https://get.docker.com | sh

      - name: Install dive
        run: |
          DIVE_VERSION=$(curl -sL "https://api.github.com/repos/wagoodman/dive/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
          ARCH="arm64"
          curl -OL https://github.com/wagoodman/dive/releases/download/v${DIVE_VERSION}/dive_${DIVE_VERSION}_linux_${ARCH}.deb
          apt install ./dive_${DIVE_VERSION}_linux_${ARCH}.deb

      - name: Log in Container registry
        run: docker login gitea.eldolfin.top -u oscar -p ${{ secrets.REGISTRY_RW_TOKEN }}

      - name: Build and push panel docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: gitea.eldolfin.top/eldolfin/wol-panel:latest
          file: ./wol-panel/Dockerfile
          context: ./wol-panel
          build-args: REGISTRY_RW_TOKEN=${{ secrets.REGISTRY_RW_TOKEN }}

      - name: Build and push api docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: gitea.eldolfin.top/eldolfin/wol-api:latest
          file: ./wol-api/Dockerfile
          context: ./wol-api

      - name: Dive panel
        run: CI=true dive gitea.eldolfin.top/eldolfin/wol-panel:latest --highestUserWastedPercent disabled

      - name: Dive api
        run: CI=true dive gitea.eldolfin.top/eldolfin/wol-api:latest --highestUserWastedPercent disabled

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-and-push-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Stack Deploy
        uses: cssnr/stack-deploy-action@v1
        with:
          name: wol
          file: ./deploy/docker-compose.yml
          host: 192.168.1.1
          user: oscar
          ssh_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
