name: "Build docker image"
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Docker
        run: curl -fsSL https://get.docker.com | sh
        
      - name: Install dive
        run: |
          DIVE_VERSION=$(curl -sL "https://api.github.com/repos/wagoodman/dive/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
          ARCH="arm64"
          curl -OL https://github.com/wagoodman/dive/releases/download/v${DIVE_VERSION}/dive_${DIVE_VERSION}_linux_${ARCH}.deb
          apt install ./dive_${DIVE_VERSION}_linux_${ARCH}.deb

      - name: Log in Container registry
        run: docker login gitea.eldolfin.top -u oscar -p ${{ secrets.REGISTRY_RW_TOKEN }}

      - name: Build and push panel docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: gitea.eldolfin.top/eldolfin/wol-panel:latest
          file: ./wol-panel/Dockerfile
          context: ./wol-panel
      
      - name: Build and push api docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: gitea.eldolfin.top/eldolfin/wol-api:latest
          file: ./wol-api/Dockerfile
          context: ./wol-api

      - name: Dive panel
        run: CI=true dive gitea.eldolfin.top/eldolfin/wol-panel:latest

      - name: Dive api
        run: CI=true dive gitea.eldolfin.top/eldolfin/wol-api:latest
