name: Playwright Tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start development docker
        run: cd ./dev && sudo docker compose -f docker-compose.test.yml up -d --build
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        working-directory: ./wol-panel
        run: npm install
      - name: Install Playwright Browsers
        working-directory: ./wol-panel
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        working-directory: ./wol-panel
        run: npm run playwright
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: wol-panel/playwright-report/
          retention-days: 30
